### ISSUE TITLE
Clean reference to uidManager during zurvan.releaseTimers

### ISSUE THREAD

**Issue by bzdanowicz** [Lewerow/zurvan#35]
this.uidManager is not cleared during timers releasing, so checking memory usage after tests (from heap dumps) will show us leaks in zurvan.

We can clean it up after usage of uid, or we can at least call: 
this.uidManager = undefined;
in ImmediateInterceptor.prototype.release

**Comment by Lewerow** [comment]
Clean after usage of uid for sure, but also at `releaseTimers` I suppose. To be checked.

**Comment by Lewerow** [comment]
Ok, actually that's a little trickier than I thought.

I've added `uidManager` not only to match timers that are to be expired. It is also used to check whether all `clearTimeout`/`clearInterval` calls use only UIDs issued by respective `setTimeout`/`setInterval` (that user does not mix them up, for example). Therefore they cannot be removed just after usage, as this would expose `zurvan` to a number of race condtion. Unfortunately it means that it's size will grow during the testcase. However, after the testcase (at `.releaseTimers`) the object with UIDs is cleared - see `UIDManager.clear` (called from `TimerRepository.releaseAll`, called from `TimerInterceptor.clearTimer`, called from `AllTimersInterceptor.relase`, called from `zurvan.releaseTimers()`). Additionally, each `.interceptTimers` causes each `TimerInterceptor` (one for timeouts and one for intervals) to create new `TimerRepository`, which is the owner of `UIDManager`. 

Basing on this I believe that `UIDManager` does not actually leak, but only increases size due to historical data. I think it shouldn't be a problem in any test case of reasonable size (perhaps a problem during stability testing, but `zurvan` is rather meant for lower-level tests), and data is cleared during releasing timers, so doesn't leak between testcases.

Can you provide some minimal example of a script that you beleive causes a leak? Is it possible that your production code kept `uid` somewhere, therefore keeping also `UIDManager` alive (due to closure features) ?

**Comment by Lewerow** [comment]
Whoops, didn't look closely. You're right about `ImmediateInterceptor`, I'll fix it right away

**Comment by Lewerow** [comment]
Fixed in d88b7b9
